# -*- coding: utf-8 -*-
"""ACO for TSP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F0NCsvGgokDmr-p9QiCP9UeLmbqH7mCn
"""

import numpy as np

def initialize_pheromone(n_cities):
    return np.ones((n_cities, n_cities)) / n_cities

def path_length(path, distances):
    length = 0
    for i in range(len(path)):
        length += distances[path[i - 1], path[i]]
    return length

def transition_probabilities(current, visited, pheromone, distances, alpha, beta):
    n_cities = len(distances)
    pheromone_row = pheromone[current]
    distances_row = distances[current]

    probabilities = []
    for city in range(n_cities):
        if city in visited:
            probabilities.append(0)
        else:
            pheromone_factor = pheromone_row[city] ** alpha
            heuristic_factor = (1.0 / distances_row[city]) ** beta if distances_row[city] > 0 else 0
            probabilities.append(pheromone_factor * heuristic_factor)

    total = sum(probabilities)
    if total == 0:
        probabilities = [1 if city not in visited else 0 for city in range(n_cities)]
        total = sum(probabilities)
    probabilities = [p / total for p in probabilities]
    return probabilities

def generate_path(start, pheromone, distances, alpha, beta):
    path = [start]
    visited = set(path)
    n_cities = len(distances)

    for _ in range(n_cities - 1):
        current = path[-1]
        probabilities = transition_probabilities(current, visited, pheromone, distances, alpha, beta)
        next_city = np.random.choice(range(n_cities), p=probabilities)
        path.append(next_city)
        visited.add(next_city)
    return path

def spread_pheromone(all_paths, pheromone):
    for path, length in all_paths:
        for i in range(len(path)):
            from_city = path[i - 1]
            to_city = path[i]
            pheromone[from_city, to_city] += 1.0 / length

def ant_colony_optimization(distances, n_ants, n_iterations, decay, alpha=1, beta=2):
    n_cities = len(distances)
    pheromone = initialize_pheromone(n_cities)
    best_path = None
    best_length = float('inf')

    for iteration in range(n_iterations):
        all_paths = []
        for _ in range(n_ants):
            path = generate_path(0, pheromone, distances, alpha, beta)
            length = path_length(path, distances)
            all_paths.append((path, length))

        spread_pheromone(all_paths, pheromone)
        pheromone *= decay

        shortest_path = min(all_paths, key=lambda x: x[1])
        if shortest_path[1] < best_length:
            best_length = shortest_path[1]
            best_path = shortest_path[0]

        print(f"Iteration {iteration+1}: shortest path length = {best_length:.2f}")

    return best_path, best_length

if __name__ == "__main__":
    distances = np.array([
        [0, 2, 2, 5, 7],
        [2, 0, 4, 8, 2],
        [2, 4, 0, 1, 3],
        [5, 8, 1, 0, 2],
        [7, 2, 3, 2, 0]
    ])

    best_path, best_length = ant_colony_optimization(distances, n_ants=10, n_iterations=5, decay=0.95, alpha=1, beta=2)
    print("\nBest path found:", best_path)
    print(f"Best path length: {best_length:.2f}")